/*
VueNm
v1.46
NamaMu Dania
*/

const Src = {
  // main NamaMu's files
  Nm_Logo: '/Images/Logo/NamaMu_logo_v6.0-1_cropped.png',
  Nm_Bg_Light: '/Images/Backgrounds/fajr_IMG_20260606_055622080.jpg',
  Nm_Bg_Dark: '/Images/Backgrounds/beforesunrise_IMG_20260513_060240917.jpg',
  // for About.vue
  // cowo
  Ahmedeeya_1: '/Images/Ahmedeeya/ahmedeeya_1.jpg',
  Ahmedeeya_2: '/Images/Ahmedeeya/ahmedeeya_2.jpg',
  Ahmedeeya_3: '/Images/Ahmedeeya/ahmedeeya_3.jpg',
  Ahmedeeya_4: '/Images/Ahmedeeya/ahmedeeya_4.jpg',
  Ahmedeeya_5: '/Images/Ahmedeeya/ahmedeeya_5.jpg',
  Ahmedeeya_6: '/Images/Ahmedeeya/ahmedeeya_6.jpg',
  Ahmedeeya_7: '/Images/Ahmedeeya/ahmedeeya_7.jpg',
  Ahmedeeya_8: '/Images/Ahmedeeya/ahmedeeya_8.jpg',
  Ahmedeeya_9: '/Images/Ahmedeeya/ahmedeeya_9.jpg',
  Ahmedeeya_10: '/Images/Ahmedeeya/ahmedeeya_10.jpeg',
  Ahmedeeya_11: '/Images/Ahmedeeya/ahmedeeya_11.jpg',
  Ahmedeeya_12: '/Images/Ahmedeeya/ahmedeeya_12.jpg',
  Ahmedeeya_13: '/Images/Ahmedeeya/ahmedeeya_13.jpg',
  Ahmedeeya_14: '/Images/Ahmedeeya/ahmedeeya_14.jpg',
  Ahmedeeya_15: '/Images/Ahmedeeya/ahmedeeya_15.jpg',
  Ahmedeeya_16: '/Images/Ahmedeeya/ahmedeeya_16.jpg',
  D3f_1: '/Images/D3f/d3f_1.jpg',
  LordDikz_1: '/Images/LordDikz/dikz_1.jpg',
  LordDikz_2: '/Images/LordDikz/dikz_2.jpg',
  LordDikz_3: '/Images/LordDikz/dikz_3.png',
  SepuhHafif_1: '/Images/SepuhHafif/hafifalbar_1.jpg',
  // cewe
  AtminNovyA_1: '/Images/AtminNovyA/sasaa_1.jpg',
  AtminNovyA_2: '/Images/AtminNovyA/sasaa_2.jpg',
  AtminNovyA_3: '/Images/AtminNovyA/sasaa_3.jpg',
  AtminNovyA_4: '/Images/AtminNovyA/sasaa_4.jpg',
  AtminNovyA_5: '/Images/AtminNovyA/sasaa_5.jpg',
  AtminNovyA_6: '/Images/AtminNovyA/sasaa_6.jpg',
  AtminNovyA_7: '/Images/AtminNovyA/sasaa_7.jpg',
  AtminNovyA_8: '/Images/AtminNovyA/sasaa_8.jpg',
  AtminNovyA_9: '/Images/AtminNovyA/sasaa_9.jpg',
  Afiva_1: '/Images/Afiva/afiva_1.webp',
  Afiva_2: '/Images/Afiva/afiva_2.webp',
  AuthorMia_1: '/Images/AuthorMia/lafina_1.jpg',
  FirAmelia_1: '/Images/FirAmelia/firamelia_1.jpg',
  FirAmelia_2: '/Images/FirAmelia/firamelia_2.jpg',
  FirAmelia_3: '/Images/FirAmelia/firamelia_3.jpg',
  FirAmelia_4: '/Images/FirAmelia/firamelia_4.jpg',
  FirAmelia_5: '/Images/FirAmelia/firamelia_5.jpg',
  FirAmelia_6: '/Images/FirAmelia/firamelia_6.jpg',
  Lutfia_1: '/Images/Lutfia/lutfia_1.jpg',
  Lutfia_2: '/Images/Lutfia/lutfia_2.jpg',
  Lutfia_3: '/Images/Lutfia/lutfia_3.jpg',
  Lutfia_4: '/Images/Lutfia/lutfia_4.jpg',
  Lutfia_5: '/Images/Lutfia/lutfia_5.jpg',
  Lutfia_6: '/Images/Lutfia/lutfia_6.jpg',
  Lutfia_7: '/Images/Lutfia/lutfia_7.png',
  Lutfia_8: '/Images/Lutfia/lutfia_8.jpg',
  Lutfia_9: '/Images/Lutfia/lutfia_9.png',
  Lutfia_10: '/Images/Lutfia/lutfia_10.png',
  Lutfia_11: '/Images/Lutfia/lutfia_11.jpg',
  Lutfia_12: '/Images/Lutfia/lutfia_12.png',
  Lyra_1: '/Images/Lyra/lyra_1.webp',
  Lyra_2: '/Images/Lyra/lyra_2.jpeg',
  Myunica_1: '/Images/Myunica/yunica_1.jpg',
  Pellownie_1: '/Images/Pellownie/veronica_1.jpg',
}
export default Src
